extends: ../config.yaml

training:
  log_at_flops: [6.0e17, 1.0e18, 3.0e18, 6.0e18, 8.0e18, 1.0e19]

model:
  encoder:
    embed_dim: 192
    depth: 6
    num_heads: 3
  decoder:
    base_channels: 24
    latent_dim: null

wandb:
  notes: 'Scaling, e192, d6'
  run_name: 'ns-e192-d6'

trainer:
  run_num: 'ns-e192-d6'
