extends: base.yaml

training:
  log_at_flops: [6.0e17, 1.0e18, 3.0e18, 6.0e18, 8.0e18, 1.0e19]

model:
  encoder:
    embed_dim: 768
    depth: 16
    num_heads: 12
  decoder:
    base_channels: 96
    latent_dim: null

wandb:
  notes: 'Scaling, e768, d16'
  run_name: 'ns-e768-d16'

trainer:
  run_num: 'ns-e768-d16'
